baseURL = "https://ethen-cao.github.io/ethenslab/"
theme = "PaperMod"
publishDir = "docs"
title = "Ethen 的实验室"

[params]
  description = "一个关于Android以及智能座舱的开发知识库。"
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowWordCount = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "Android系统开发"
    url = "/android-dev/"
    weight = 10
  [[menu.main]]
    name = "Android Automotive"
    url = "/android-automotive-os-dev/"
    weight = 20
  [[menu.main]]
    name = "QNX开发"
    url = "/qnx/"
    weight = 25
  [[menu.main]]
    name = "智能座舱方案"
    url = "/ivi-solution/"
    weight = 30
  [[menu.main]]
    name = "Explore AI"
    url = "/explore-ai"
    weight = 40
