baseURL = "https://ethen-cao.github.io/ethenslab/"
languageCode = 'en-us'
title = "Ethen's Lab"
theme = "PaperMod"
publishDir = "docs"
[params]
  author = "Ethen CQL"
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
