"""Display interfaces in the current QNX host and Android guest source tree."""
from html import escape

from software_display_graph import render_graph


QNX_DISPLAY = 'QNX/HQX-4-5-5-0_HLOS_DEV_QNX/apps/qnx_ap/AMSS/multimedia/display/Hoya/'
ANDROID = 'android/android/'
QNX_HAB = 'QNX/HQX-4-5-5-0_HLOS_DEV_QNX/apps/qnx_ap/AMSS/multimedia/hab/driver/hypervisor/qvm/qnx/'
GRAPHICS_CONFIG = 'bsp/apps/qnx_ap/boards/display/adp_star_sda8295/config/graphics_HBEZ.conf'
ANDROID_GPU = ANDROID+'vendor/qcom/proprietary/prebuilt_HY11/target/product/msmnile_gvmq/'
QNX_GPU = 'bsp/apps/qnx_ap/prebuilt/aarch64le/'


def module(mid, name, domain, short, duty, source, status='', kind='component'):
    return dict(id=mid, name=name, domain=domain, short=short, duty=duty,
                source=source, status=status, kind=kind)


MODULES = [
    module('display-cluster', 'ClusterApp', 'qnx', 'Kanzi HMI',
           'ClusterApp 使用 Kanzi 构建仪表界面，通过 Screen、EGL 和 GLES 提交窗口画面。',
           'cluster_source_code/apps/clusterkanzi/ClusterHMI/CMakeLists.txt:178、188–190。',
           'QNX 构建链接已核实；窗口和屏幕分配以运行配置为准。'),
    module('display-qnx-render', 'libESXEGL_Adreno.so / libESXGLESv2_Adreno.so', 'qnx', 'EGL / GLES rendering',
           '提供图形上下文与绘制接口，将渲染结果写入窗口缓冲。',
           'bsp/apps/qnx_ap/target/filesets/qc.gfx.umd.build:7–9；'+GRAPHICS_CONFIG+':3–5；'+QNX_GPU+'usr/lib/graphics/qc/libESXGLESv2_Adreno.so 的 ELF 依赖包含 libGSLUser.so。'),
    module('display-screen', 'screen / libscreen.so.1', 'qnx', 'Windows / composition',
           '管理窗口、图像缓冲和合成路径，按 graphics 配置使用 OpenWFD 显示驱动。',
           'bsp/apps/qnx_ap/target/filesets/common.qnx.early.screen.build:1、9；bsp/apps/qnx_ap/boards/display/adp_star_sda8295/config/graphics_HBEZ.conf:3–15。'),
    module('display-wfd-client', 'libopenwfd_qnx.so / libopenwfd.so', 'qnx', 'Screen client / generic client',
           'Screen 加载 libopenwfd_qnx.so；wfd_be 链接 libopenwfd.so。两种客户端通过本地 read/write IPC 向显示服务提交请求并读取应答。',
           'bsp/apps/qnx_ap/target/filesets/qc.display.build:53–54；bsp/apps/qnx_ap/boards/display/adp_star_sda8295/config/graphics_HBEZ.conf:11、14；QNX/HQX-4-5-5-0_HLOS_DEV_QNX/apps/qnx_ap/AMSS/multimedia/display/Hoya/wfd_be_qnx/common.mk:93；wfd_client_gen/common.mk:101；wfd_client_qnx/src/user_qnx_utils.c:50、715–718。'),
    module('display-wfd-be', 'wfd_be', 'qnx', 'Guest display backend',
           '接收来宾 OpenWFD wire 请求，导入 HAB 缓冲 ID，并用对应 PMEM handle 创建图像源。',
           QNX_DISPLAY+'wfd_be_qnx/src/host_hab_utils.c:168、191；wfd_be_qnx/src/wire_host.c:1558、1580、1607。',
           '源码接口已核实；运行实例和通道配置需结合启动配置确认。'),
    module('display-wfd-server', 'openwfd_server', 'qnx', 'Display service',
           '承载本地 OpenWFD 请求处理和显示运行时；核心库、QDI/HAL 与面板库属于其实现组件。',
           QNX_DISPLAY+'wfd_server_qnx/src/wfd_server.c；openwfd/src/wfd_clientmgr.c。',
           '服务实例、设备和输出映射以板级配置为准。'),
    module('display-wfd-core', 'openwfd_core', 'qnx', 'Linked in server · WFD objects',
           '管理图像源、端口、管线绑定与提交，调用 QDI 执行显示配置。openwfd_core 以静态库形式链接进 openwfd_server。',
           'QNX/HQX-4-5-5-0_HLOS_DEV_QNX/apps/qnx_ap/AMSS/multimedia/display/Hoya/openwfd/common.mk:126；wfd_server_qnx/common.mk:117–139；openwfd/src/source.c、pipeline.c、port.c、wfd_commitmgr.c。'),
    module('display-mdss', 'qdi / qdiplatform_s8155', 'qnx', 'Linked in server · MDP / MDSS',
           'qdi 与 qdiplatform_s8155 负责显示内存映射、图层和扫描管线配置，并调用面板接口。当前 server 链接其静态版本及 halmdp / halmdss。',
           'QNX/HQX-4-5-5-0_HLOS_DEV_QNX/apps/qnx_ap/AMSS/multimedia/display/Hoya/wfd_server_qnx/common.mk:117–139；qdidriver/source/platform/memmgr/mdss_platform_memmgr.c；platform/mdss/mdss_drv.c；coredriver/mdp/mdp_dc.c:599–607。动态产物名见 bsp/apps/qnx_ap/target/filesets/qc.display.build:26–27、46–47。'),
    module('display-interface-driver', 'qdidsihost / qdidphost', 'qnx', 'Linked in server · DSI / DP',
           'qdidsihost 与 qdidphost 配置 DSI/DP 模式、链路时序、时钟和 PHY，经 haldsi / haldp 访问硬件；当前 server 链接静态版本。',
           'QNX/HQX-4-5-5-0_HLOS_DEV_QNX/apps/qnx_ap/AMSS/multimedia/display/Hoya/wfd_server_qnx/common.mk:117–139；qdidriver/source/coredriver/dsi/dsi_host.c；dp/dp_host.c。动态产物名见 bsp/apps/qnx_ap/target/filesets/qc.display.build:29–30、48、51。',
           '驱动与 HAL 为服务内部组件；启用的接口以板级配置为准。'),
    module('display-screen-config', 'graphics.conf', 'qnx', 'Screen configuration',
           '配置 QNX Screen 的图形库、OpenWFD 客户端驱动、显示模式和窗口类映射。',
           GRAPHICS_CONFIG+'；bsp/apps/qnx_ap/target/filesets/qc.display.build:108；bsp/apps/qnx_ap/target/hypervisor/host/out_8540/platform_variables.sh:94–95。',
           'Screen 的静态配置输入；具体内容以启动时选用文件为准。', kind='config'),
    module('display-wfd-config', 'qcdisplaycfg.xml', 'qnx', 'OpenWFD configuration',
           '配置 OpenWFD Server 的客户端、设备、端口、管线及面板和桥接器库。',
           'bsp/apps/qnx_ap/boards/display/adp_star_sda8295/config/qcdisplaycfg_HBEZ.xml:83–102、332–350；'+QNX_DISPLAY+'qdidriver/source/coredriver/drvconfig/mdss_drvconfig.c:35–36、4975–4985、5184–5195；bsp/apps/qnx_ap/target/filesets/qc.display.build:106。',
           'OpenWFD Server 的静态配置输入；设备映射以启动时选用文件为准。', kind='config'),
    module('display-panel-driver', 'libDSI_COMMON_QC_0.so / libDP0_COMMON_QC.so / libbridgechip_client.so', 'qnx', 'Panel adapters (examples) / bridge IPC',
           '按配置加载面板库，设置显示模式、电源和输出接口；通过 libbridgechip_client.so 访问桥接服务。图中列出代表库，完整选用清单见模块来源。',
           'bsp/apps/qnx_ap/boards/display/adp_star_sda8295/config/qcdisplaycfg_HBEZ.xml:334、362、391、463、535：libDSI_COMMON_QC_0.so、libDSI_COMMON_QC_1.so、libDP0_COMMON_QC.so、libDP0_COMMON_MST_QC.so、libDP2_COMMON_QC.so。boards/display/common/panels/DSI_COMMON_QC_0/common.mk:63、DP0_COMMON_QC/common.mk:62 链接 bridgechip_client。target/filesets/qc.display.build:58–65、76 定义产物。',
           '具体面板库、桥接器和物理连接以板级配置为准。'),
    module('display-qnx-gsl', 'libGSLUser.so', 'qnx', 'Host GPU APIs',
           '提供主机图形设备、上下文和内存接口，通过 QNX IPC 调用 KGSL。',
           QNX_GPU+'usr/lib/graphics/qc/libGSLUser.so：/dev/kgsl-3D、ioctl_kgsl_*、MsgSendv；bsp/apps/qnx_ap/target/filesets/qc.gfx.build:12。',
           '预编译库；接口边界由二进制依赖和符号确认。'),
    module('display-qnx-gpu', 'kgsl / GSLKernel.so', 'qnx', 'GPU driver',
           '提供 GPU 设备接口，处理图形上下文、内存映射和命令提交，控制 Adreno GPU 硬件。',
           'bsp/apps/qnx_ap/target/filesets/qc.gfx.build:6、11–12；'+QNX_GPU+'usr/lib/graphics/qc/GSLKernel.so。',
           'QNX 驱动进程及其实现库；内部调度策略未展开。'),
    module('display-qnx-hab', 'libuhab.so / hab', 'qnx', 'HAB host endpoint',
           '提供主机侧 HAB 消息与内存共享接口；UHAB 库将 habmm_* 调用交给 QNX HAB 资源管理器。',
           'bsp/apps/qnx_ap/AMSS/platform/qal/clients/uhab/uhab.c:183、493、661、717；bsp/apps/qnx_ap/AMSS/multimedia/hab/driver/os/qnx/hab_ldd.c:911；target/filesets/qc.mm.common.build:34。',
           'UHAB 是用户态库，HAB 是资源管理器；跨 VM 传输由 QVM 适配层承载。'),
    module('display-apps', 'Android UI Applications', 'aaos', 'View · Canvas · SurfaceView',
           '使用 View、Canvas 或 SurfaceView 构建界面，并选择对应的窗口绘制路径。',
           ANDROID+'frameworks/base/core/java/android/view/ViewRootImpl.java:2231、8319。',
           '调用方集合；具体应用和显示分配以产品配置为准。'),
    module('display-viewroot', 'ViewRootImpl / ViewTree', 'aaos', 'UI thread · traversal · draw',
           '在 UI 线程中组织 View 树的测量、布局和绘制，维护窗口 Surface，并向窗口服务提交布局请求。',
           ANDROID+'frameworks/base/core/java/android/view/ViewRootImpl.java:1648–1659；performTraversals、performDraw。'),
    module('display-threaded-renderer', 'ThreadedRenderer', 'aaos', 'syncAndDrawFrame · JNI',
           '更新根 RenderNode，通过 JNI 将本帧绘制任务交给 HWUI 的 RenderThread。',
           ANDROID+'frameworks/base/core/java/android/view/ThreadedRenderer.java:693、733、793–811；frameworks/base/libs/hwui/jni/android_graphics_HardwareRenderer.cpp:261–269。'),
    module('display-surfaceview', 'SurfaceView', 'aaos', 'Independent Surface',
           '为视频或独立渲染内容创建单独的 Surface 和 BLAST 队列，随 View 布局更新其位置与尺寸。',
           ANDROID+'frameworks/base/core/java/android/view/SurfaceView.java:1143、1240。'),
    module('display-recording', 'RecordingCanvas / RenderNode', 'aaos', 'Java API · display list',
           '把 View 的绘制操作记录到 RenderNode，由 HWUI 在渲染线程中执行。',
           ANDROID+'frameworks/base/graphics/java/android/graphics/RenderNode.java:444–480；frameworks/base/core/java/android/view/ThreadedRenderer.java:733。'),
    module('display-native-client', 'Native / 3D Engine', 'aaos', 'GLES or Vulkan · Surface client',
           '使用 GLES 或 Vulkan 绘制内容，通过目标 ANativeWindow 获取缓冲并提交帧。',
           ANDROID+'frameworks/native/libs/nativewindow/ANativeWindow.cpp:293–300；frameworks/native/opengl/libs/EGL/Loader.cpp；frameworks/native/vulkan/libvulkan/driver.cpp。',
           '原生渲染客户端的功能入口，具体引擎由应用选择。'),
    module('display-surface', 'Surface / ANativeWindow', 'aaos', 'Dequeue · queueBuffer',
           '提供帧生产端窗口接口，获取可写缓冲，并将完成的帧及同步 fence 交给缓冲队列。',
           ANDROID+'frameworks/native/libs/nativewindow/ANativeWindow.cpp:293–300；frameworks/base/native/android/native_window_jni.cpp:30；frameworks/native/libs/gui/Surface.cpp。'),
    module('display-api-loader', 'GLES / Vulkan APIs & Loaders', 'aaos', 'libEGL · libGLESv2 · libvulkan',
           '提供 Android 的 EGL、GLES 和 Vulkan 入口，按配置加载对应的厂商图形驱动。',
           ANDROID+'frameworks/native/opengl/libs/EGL/Loader.cpp:210–262；frameworks/native/vulkan/libvulkan/driver.cpp。'),
    module('display-wms', 'WindowManagerService', 'aaos', 'Window state · layer transactions',
           '管理窗口状态、层级和可见性，通过 SurfaceControl 事务更新合成场景。',
           ANDROID+'frameworks/base/services/core/java/com/android/server/wm/WindowManagerService.java:2986；com/android/server/wm/DisplayContent.java:4879。'),
    module('display-dms', 'DisplayManagerService', 'aaos', 'Logical displays · display policy',
           '管理逻辑显示、显示属性和策略，协调框架中的显示状态。',
           ANDROID+'frameworks/base/services/core/java/com/android/server/display/DisplayManagerService.java:1487；LocalDisplayAdapter.java:823、1011。'),
    module('display-bufferqueue', 'BLASTBufferQueue', 'aaos', 'Per-Surface queue · buffer transactions',
           '接收 Surface 提交的缓冲与 fence，通过 SurfaceControl 事务把帧交给 SurfaceFlinger。',
           ANDROID+'frameworks/native/libs/gui/BLASTBufferQueue.cpp:143、570；BufferQueueProducer.cpp；BufferQueueConsumer.cpp。'),
    module('display-flinger', 'SurfaceFlinger', 'aaos', 'Layer state · composition',
           '消费图层缓冲，选择合成方式，将图层或 client target 交给 Composer。',
           ANDROID+'frameworks/native/services/surfaceflinger/SurfaceFlinger.cpp。'),
    module('display-gralloc', 'gralloc', 'aaos', 'Allocate · import · buffer handles',
           '按尺寸、格式与 usage 分配或导入图像缓冲，提供供 GPU 和显示路径使用的句柄。',
           ANDROID+'hardware/qcom/display/gralloc/gr_buf_mgr.cpp:1011；gr_dma_mgr.cpp。'),
    module('display-composer', 'HWC Composer', 'aaos', 'Validate · present · layer policy',
           '接收图层与 client target，执行 validate/present，并调用 SDM 完成显示提交。',
           ANDROID+'hardware/qcom/display/sdm/libs/hwc2/hwc_session.cpp；hwc_display.cpp；composer-aidl。',
           '源码包含 HWC2 与 AIDL 实现；部署接口版本需按运行配置确认。'),
    module('display-sdm', 'SDM', 'aaos', 'Composition plan · display commit',
           '规划图层与硬件资源，组织显示提交，并经 DRM 适配层访问来宾显示驱动。',
           ANDROID+'hardware/qcom/display/sdm/libs/core/display_base.cpp；core/drm/hw_device_drm.cpp。'),
    module('display-drm-adapter', 'DRM Adapter', 'aaos', 'DRM objects · atomic submission',
           '将 SDM 的显示配置转换为 DRM 对象、属性与提交请求。',
           ANDROID+'hardware/qcom/display/libdrmutils/drm_master.cpp:166、183；vendor/qcom/proprietary/display/sde-drm/drm_atomic_req.cpp:153。'),
    module('display-renderengine', 'RenderEngine', 'aaos', 'GLES / SkiaGL client composition',
           '按 SurfaceFlinger 请求执行 GPU 合成，通过 GLES 或 SkiaGL 生成 client target 缓冲。',
           ANDROID+'frameworks/native/libs/renderengine/RenderEngine.cpp:29–53；services/surfaceflinger。'),
    module('display-hwui', 'RenderThread / HWUI', 'aaos', 'libhwui · Skia GPU backend',
           '在应用进程的 RenderThread 中执行视图绘制，按配置选择 SkiaGL 或 SkiaVulkan，并向 Surface 队列提交帧。',
           ANDROID+'frameworks/base/libs/hwui/renderthread/CanvasContext.cpp:76–90；pipeline/skia/SkiaOpenGLPipeline.cpp:137–152；SkiaVulkanPipeline.cpp:115–128。',
           '具体渲染后端由运行配置选择。'),
    module('display-opengl', 'OpenGL / EGL Subdriver', 'aaos', 'Adreno EGL / GLES implementation',
           '承接 EGL/GLES 调用，将图形操作转换为 Adreno 命令，并通过 GSL Client 接入 Guest GPU 驱动。',
           ANDROID_GPU+'Android.mk:1443–1479；vendor/lib64/egl/libEGL_adreno.so、libGLESv2_adreno.so 的 ELF 依赖包含 libgsl.so。',
           'AOSP EGL/GLES 入口加载厂商实现；厂商库为预编译组件。'),
    module('display-vulkan', 'Vulkan Driver', 'aaos', 'vulkan.adreno.so · Vulkan ICD',
           '由 AOSP Vulkan loader 加载，编译和提交 Vulkan 工作负载，调用 GSL Client 提供的设备接口。',
           ANDROID_GPU+'Android.mk:1569–1577；vendor/lib64/hw/vulkan.adreno.so 的 ELF 依赖包含 libgsl.so。',
           'HWUI 的 SkiaVulkan 分支可使用该驱动；具体后端由运行配置选择。'),
    module('display-gsl-client', 'GSL Client', 'aaos', 'libgsl.so · /dev/hgsl',
           '提供 Guest 用户态图形设备接口，将厂商图形库的操作转换为 /dev/hgsl ioctl。',
           ANDROID_GPU+'Android.mk:2213–2221；vendor/lib64/libgsl.so 包含 /dev/hgsl 接口；'+ANDROID+'kernel_platform/msm-kernel/drivers/soc/qcom/hgsl/hgsl.c。',
           '用户态闭源库；接口边界由驱动源码与二进制依赖确认。'),
    module('display-wfd-fe', 'msm-hyp / wfd_kms', 'aaos', 'WFD wire frontend · HAB',
           '实现来宾 DRM 显示端点，经 HAB 发送 OpenWFD 请求与缓冲 ID，并接收提交、垂直同步和热插拔事件。',
           ANDROID+'vendor/qcom/opensource/display-drivers/msm-hyp/wfd/wfd_kms.c:1089、1122、1932、2379–2394；wire_user.c；user_hab_utils.c。'),
    module('display-android-gpu', 'HGSL', 'aaos', 'Guest GPU driver · RPC / shared command queues',
           '管理 Guest 图形上下文、内存和同步；控制请求使用 GSL RPC，命令提交可使用共享队列与门铃通知。',
           ANDROID+'kernel_platform/msm-kernel/drivers/soc/qcom/hgsl/hgsl_hyp_socket.c:19、50；hgsl_hyp.c:1400；hgsl.c:1099、1116；arch/arm64/configs/vendor/autogvm.config:110。'),
    module('display-khab', 'Guest HAB / KHAB', 'aaos', 'msm_hab · MM_GFX / MM_DISP',
           '为 HGSL 和显示前端提供 HAB 消息及内存共享接口，分别承载 MM_GFX 图形通道和 MM_DISP 显示通道。',
           ANDROID+'kernel_platform/msm-kernel/drivers/soc/qcom/hab/khab.c:9；hab/Makefile:18、38；hgsl/hgsl_hyp_socket.c:19、50；vendor/qcom/opensource/display-drivers/msm-hyp/wfd/user_hab_utils.c:84–108、201、230、643。',
           'KHAB 是 msm_hab 内部 API 层。'),
    module('display-gsl-be', 'gsl_hab_server', 'qnx', 'Guest graphics backend',
           '通过 UHAB/HAB 接收 Guest 图形请求，调用主机 GSL 接口管理图形设备、上下文和内存。',
           'bsp/apps/qnx_ap/target/filesets/qc.gfx.be.build:4；launcher_scripts/vgfx.c:8–24；'+QNX_GPU+'usr/bin/gsl_hab_server-qvmhost 的 ELF 依赖含 libuhab.so、libGSLUser.so，并导入 habmm_*、gsl_* API。',
           '服务与 GSL 库为预编译组件；内部队列调度未展开。'),
    module('display-vm-memory', 'QVM Shared Communication Pipes', 'platform', 'HAB transport · shared regions',
           '建立 QVM 共享通信管道，供 HAB 消息收发使用；图像内存由缓冲导入与映射接口管理。',
           QNX_HAB+'hab_qvm_qnx.c:140–175；qvm_comm_qnx.c:21、60。'),
    module('display-vm-notify', 'VM Event Notification', 'platform', 'QVM shared-memory notifications',
           '通过 QVM 共享内存通知接口唤醒对端处理 HAB 数据。',
           QNX_HAB+'hab_qvm_qnx.c:140–175；qvm_comm_qnx.c:21、60。',
           'hyp_shm_* / hyp_shm_poke 为源码接口；具体 VM 配置另行定义。'),
    module('display-gpu', 'GPU', 'hardware', 'Render · compose · write frames',
           '执行图形绘制与 GPU 合成，将结果写入图像缓冲。',
           'bsp/apps/qnx_ap/target/filesets/qc.gfx.build、qc.gfx.umd.build；'+QNX_GPU+'usr/lib/graphics/qc/GSLKernel.so；'+ANDROID+'kernel_platform/msm-kernel/drivers/soc/qcom/hgsl/hgsl.c；hardware/qcom/display/gralloc/gr_buf_mgr.cpp。',
           '硬件职责抽象；图中不指定芯片型号。'),
    module('display-buffers', 'Frame Buffers', 'hardware', 'Pixel storage · shared references',
           '保存应用帧和合成结果；GPU 写入像素，显示引擎读取选定扫描源。',
           ANDROID+'hardware/qcom/display/gralloc/gr_buf_mgr.cpp；'+QNX_DISPLAY+'wfd_be_qnx/src/host_hab_utils.c；qdidriver/source/platform/memmgr/mdss_platform_memmgr.c。',
           kind='memory'),
    module('display-dpu', 'Display Engine / DPU', 'hardware', 'Read scanout · compose · output',
           '按驱动配置读取扫描缓冲，执行硬件图层处理并向输出接口发送像素。',
           QNX_DISPLAY+'qdidriver/source/coredriver/mdp；source/platform/memmgr/mdss_platform_memmgr.c。',
           '显示硬件抽象；DPU 实例与屏幕对应关系以配置为准。'),
    module('display-output', 'DSI / DP Controller & PHY', 'hardware', 'Output controller · physical interface',
           '接收显示引擎的扫描像素，由 DSI/DP 控制器组织链路传输，PHY 输出电气信号。',
           '硬件职责由接口驱动与 HAL 的寄存器操作体现：'+QNX_DISPLAY+'qdidriver/source/coredriver/dsi；dp；wfd_server_qnx/common.mk:118–128。',
           '硬件组件；接口实例与物理连接以板级配置为准。'),
    module('display-link', 'Panel Link / Bridge', 'output', 'Configured link adaptation',
           '按板级设计适配显示输出与面板之间的物理链路。',
           '板级显示配置与面板/桥接驱动接口；'+QNX_DISPLAY+'qdidriver/source/coredriver/mdp/mdp_dc.c。',
           '逻辑链路抽象；具体桥接器及连接拓扑待按产品配置核对。'),
    module('display-panel', 'Display Panels', 'output', 'Configured displays',
           '接收所分配显示链路的像素并呈现画面。',
           'bsp/apps/qnx_ap/boards/display/adp_star_sda8295/config/qcdisplaycfg_HBEZ.xml。',
           '端口、分辨率和显示硬件分配以产品配置为准。'),
]


FLOWS = [
    ('1 · ClusterApp → libESXEGL_Adreno / libESXGLESv2_Adreno → screen',
     'Control / buffer references', 'Screen · EGL · GLES',
     'QNX 构建已链接 Screen、EGL 和 GLES；应用生成窗口帧并提交缓冲。'),
    ('2 · screen → libopenwfd_qnx.so ↔ openwfd_server',
     'Control / replies', 'Local QNX read/write IPC',
     '客户端向 /dev/openwfd_server_<id> 写入 wire 请求并读取应答；像素保留在图像缓冲中。'),
    ('3 · WindowManagerService / DisplayManagerService → SurfaceFlinger',
     'Control', 'Framework APIs · SurfaceControl transactions',
     '框架管理窗口和逻辑显示状态，SurfaceFlinger 接收图层与显示事务。'),
    ('4 · ViewRootImpl / ThreadedRenderer / RenderNode → HWUI; Surface / ANativeWindow → BLASTBufferQueue → SurfaceFlinger',
     'Buffer references / synchronization', 'GraphicBuffer handles · local fences',
     'Java 视图经 HWUI 绘制；SurfaceView 和原生客户端使用各自的 Surface。完成的帧通过 BLAST 事务交给 SurfaceFlinger。'),
    ('5 · SurfaceFlinger → HWC Composer → SDM → DRM Adapter',
     'Control / buffer references', 'Validate · present · DRM atomic API',
     '选择硬件图层或 client composition，提交图层配置与所选扫描缓冲引用。'),
    ('6 · HWUI / Native clients / RenderEngine → APIs & Loaders → Adreno drivers → GSL Client → HGSL',
     'Rendering / driver calls', 'AOSP EGL/GLES or Vulkan loader · libgsl · ioctl',
     'HWUI 按配置选择 SkiaGL 或 SkiaVulkan；当前 RenderEngine 使用 GLES/SkiaGL。厂商驱动通过 libgsl 接入 HGSL。'),
    ('7 · HGSL ↔ KHAB ↔ libuhab.so / hab ↔ gsl_hab_server',
     'Control RPC / memory sharing', 'HAB MM_GFX · habmm_* · QVM transport',
     'Guest 内核 HAB API 与 QNX UHAB/HAB 通过 MM_GFX 通道承载 GSL 请求、应答和内存共享。'),
    ('8 · gsl_hab_server; QNX EGL / GLES → libGSLUser.so → kgsl / GSLKernel.so → GPU',
     'Host driver calls', 'libGSLUser.so · /dev/kgsl-3D · QNX IPC',
     'Guest 服务和主机原生图形库调用 GSL，由 KGSL 执行 GPU 设备控制。'),
    ('9 · HGSL shared command queue',
     'Command submission / notification', 'DBCQ descriptors · TCSR / GMU doorbell',
     'HGSL 支持将命令描述符写入共享队列并触发门铃；队列启用由运行配置决定，主机内部调度属于闭源实现。'),
    ('10 · gralloc ↔ Frame Buffers',
     'Buffer references', 'Allocation / import · native handles · DMA-BUF',
     '按格式与 usage 分配或导入缓冲；句柄供图形与显示组件引用。'),
    ('11 · DRM Adapter → msm-hyp / wfd_kms → Guest HAB ↔ wfd_be',
     'Control / replies', 'DRM submit · OpenWFD wire requests · HAB',
     '来宾在提交前等待本域 acquire fence，经 Guest HAB 的 MM_DISP 通道向 QNX wfd_be 发送显示请求；fence FD 保留在来宾域。'),
    ('12 · msm-hyp / wfd_kms → wfd_be → openwfd_core',
     'Buffer references', 'HAB export ID / import · PMEM handle',
     '后端导入 HAB ID，用对应 PMEM handle 创建 OpenWFD image；跨域消息携带缓冲引用。'),
    ('13 · graphics.conf → screen',
     'Configuration input', 'graphics.conf',
     'Screen 读取图形库、OpenWFD 客户端驱动、显示模式和窗口类配置。'),
    ('14 · qcdisplaycfg.xml → openwfd_server',
     'Configuration input', 'qcdisplaycfg.xml',
     '显示服务内的 QDI/MDSS 读取 XML，配置客户端、设备、端口、管线以及面板和桥接器库。'),
    ('15 · openwfd_core → qdi / qdiplatform_s8155 → panel libraries → qdidsihost / qdidphost',
     'Configuration / control', 'OpenWFD commit · QDI · panel / output interface APIs',
     '服务内的核心库与 QDI 配置图层、管线和内存映射；面板库通过 DSI/DP 接口驱动配置输出模式、链路和电源。'),
    ('16 · GPU → Frame Buffers → Display Engine / DPU → DSI / DP Controller & PHY → Panel Link → Display Panels',
     'Pixel data', 'Memory writes / scanout reads · configured physical link',
     'GPU 写入图像，显示引擎读取选定扫描缓冲并输出像素；物理路由按板级配置选择。'),
    ('17 · qdidsihost / qdidphost → DSI / DP Controller & PHY',
     'Hardware configuration', 'Driver calls · HAL register access',
     '接口驱动通过 HAL 配置控制器、PHY、时钟与链路；该配置路径独立于硬件像素传输路径。'),
    ('18 · openwfd_server → wfd_be → msm-hyp / wfd_kms → HWC / SurfaceFlinger',
     'Events / feedback', 'COMMIT_COMPLETE · VSYNC · HPD · local guest fences',
     '完成与显示事件经 HAB 返回，来宾处理事件并更新本域同步状态。QVM 的 hyp_shm_* / hyp_shm_poke 支撑 HAB 共享内存通知。'),
]


def render_display():
    groups = [('QNX Cluster', 'qnx'), ('AAOS IVI', 'aaos'),
              ('Virtualization', 'platform'), ('SoC Hardware / Memory', 'hardware'),
              ('Display Output', 'output')]
    index = ''.join(
        '<section class="sw-index-group"><h4>'+title+'</h4><ul class="sw-index-list">'
        + ''.join(
            '<li><button class="sw-index-entry" id="sw-index-'+m['id']
            +'" type="button" data-sw-module="'+m['id']+'" aria-pressed="false">'
            +'<span class="sw-index-name">'+escape(m['name'])+'</span>'
            +'<span class="sw-index-duty" lang="zh-CN">'+escape(m['duty'])
            +'</span></button></li>'
            for m in MODULES if m['domain'] == domain)
        +'</ul></section>' for title, domain in groups)
    rows = ''.join('<tr>'+''.join('<td>'+escape(cell)+'</td>' for cell in row)
                   +'</tr>' for row in FLOWS)
    controls = ''.join(
        '<button type="button" data-display-focus="'+key+'" aria-pressed="'
        +str(key == 'all').lower()+'">'+title+'</button>'
        for key, title in [('all', 'All'), ('control', 'Control calls'),
                           ('buffers', 'Buffer references'), ('pixels', 'Pixel data'),
                           ('events', 'Events / feedback')])
    return f'''
<div class="sw-page sw-display-page" id="sw-display-view" hidden>
  <div class="sw-ota-nav"><button class="sw-back" id="sw-display-back" type="button">← High-Level software architecture</button><span>Display software architecture</span></div>
  <div class="sw-ota-controls" role="group" aria-label="Highlight display interaction type"><span>Interaction paths</span>{controls}</div>
  <div class="sw-board-scroll sw-ota-scroll" aria-label="Display execution domains, software layers, shared buffers and physical output">{render_graph(MODULES)}</div>
  <div class="sw-ota-inspector" id="sw-display-inspector" role="status" aria-live="polite">Select a component to highlight its connections. Right-click to clear selection.</div>
  <section class="sw-index" aria-labelledby="sw-display-index-title"><div class="sw-section-heading"><h3 id="sw-display-index-title">Module responsibilities</h3><p lang="zh-CN">职责和源码来源列于下方；点击模块可查看源码来源；屏幕映射按产品配置核对。</p></div>{index}</section>
  <section class="sw-interfaces" aria-labelledby="sw-display-flows-title"><div class="sw-section-heading"><h3 id="sw-display-flows-title">Interfaces &amp; data flow</h3></div><div class="sw-flow-table-wrap"><table class="sw-flow-table"><thead><tr><th>Components</th><th>Flow type</th><th>API / transport</th><th>Behavior</th></tr></thead><tbody>{rows}</tbody></table></div></section>
  <div class="sw-provenance" lang="zh-CN">依据当前 QNX Hoya、Android 13 图形源码、HBEZ 图形配置与镜像清单整理，参考 GSL Host/Guest 交互图和 graphics.md 的通用渲染分层。Android 按 Java、Native、HAL、Linux Kernel 展开；左列为渲染驱动，右列为缓冲提交与显示合成。QNX 左列为显示提交链，右列为配置与 Guest / GPU 接入组件。块名采用进程、库或构建组件名；openwfd_core、QDI 和 DSI/DP host 以静态版本链接进服务。面板块列代表库，具体选用清单见模块来源。跨域传递 OpenWFD 请求、缓冲 ID 与事件，像素保存在帧缓冲中。GSL 对应 libGSLUser.so，KGSL 对应 kgsl / GSLKernel.so。共享命令队列列为 HGSL 能力；控制 RPC 经 HAB。当前跨 VM 路径使用 QVM/HAB。屏幕端口、分辨率及物理链路以板级配置为准。</div>
</div>''', {'modules': MODULES, 'flows': FLOWS}
