@startwbs
* 云端需求规划
** 稳定性管理
*** 核心 KPI
**** SystemServer Crash（系统重启）
**** Watchdog 重启
**** Kernel Panic（内核崩溃）
*** 应用稳定性
**** 千车应用崩溃率
**** 运行时崩溃率
*** 特殊重点告警
**** App 连续 Crash
**** 系统服务持续 Crash
*** Top 问题榜单
**** Top Crash
**** Top ANR
**** ANR Trace 文件
*** 问题分布画像
*** 系统重启详情
**** SystemServer 重启
**** Android Kernel 重启
**** Linux Host 重启
*** Binder 异常监控
**** Binder 异常检测
**** Dump 内存
**** Binder Stats
**** 相关 Log
*** OOM Kill 事件
**** 实时上报
*** LMK 事件
**** 实时上报
*** 文件句柄泄漏
**** 实时上报
*** 核心进程 Crash
**** 实时上报
** 性能与体验
*** 应用性能
**** 冷启动性能
***** 每小时统计
**** 资源消耗
***** 内存均值
***** 内存趋势
***** CPU 消耗
**** 主线程卡顿
***** 卡顿次数
*** 系统性能
**** CPU 利用率
***** 阈值 > 85%
***** 进程 CPU 使用率
***** 调度信息
***** Trace
**** 内存利用率
***** 阈值 > 85%
***** 进程内存占用
***** 系统压力数据
***** Trace
**** IO 性能
** 通用功能
*** 远程诊断能力
**** 远程执行 adb shell
**** 获取终端诊断信息
@endwbs
