@startuml


WindowOrganizer -> IWindowOrganizerController:applyTransaction(WindowContainerTransaction t)
IWindowOrganizerController -> WindowOrganizerController: applyTransaction(WindowContainerTransaction t)

@enduml