@startuml

skinparam ParticipantBackgroundColor #80DEEA

box "SystemUI"

end box

box "Aidl/BinderTread"
participant ITransitionPlayer
end box

box "com.android.wm.shell" #E0F7FA
  participant TransitionPlayerImpl
  participant Transitions
  participant WindowOrganizer
  participant IWindowOrganizerController
  participant WindowOrganizerController
  participant SplitScreenController

end box

ITransitionPlayer -> TransitionPlayerImpl:onTransitionReady
TransitionPlayerImpl -> Transitions:onTransitionReady

@enduml