@startyaml
UFS Partiton Layout:
    LUN 0:
        - MBR
        - Primary GPT
        - Backup GPT
        - QNX Boot Partition
        - QNX Root Partition
        - QNX Data Partition
    LUN 1:

@endyaml