@startuml
!theme plain
skinparam defaultFontColor black
skinparam sequenceArrowColor #212121
skinparam sequenceLifeLineBorderColor #757575
skinparam sequenceParticipantBorderColor #757575
skinparam sequenceParticipantBackgroundColor #FFFFFF
autonumber "[0]"

participant "Launcher\n(Task Organizer)" as Launcher
participant "ATMS / WMS\n(System Server)" as WMS
participant "SurfaceFlinger" as SF

Launcher -> WMS: startActivity(Map)
WMS -> WMS: 创建 Map Task 与 ActivityRecord
WMS -> WMS: 分配初始默认 Bounds (通常是全局 0,0)
WMS -> SF: 提交 Transaction: \n显示 Starting Window (图中的灰白块)
note right of SF: 此时触发 Bug。\nSF 直接在屏幕左侧渲染了默认位置的背景，\n用户肉眼看到闪现的色块。
WMS -> Launcher: onTaskAppeared(TaskInfo, SurfaceControl)
Launcher -> Launcher: 重新计算 TaskView 实际挂载节点与坐标
Launcher -> SF: 提交 Transaction: \n将 Map Surface 移动至正确位置或隐藏
note right of SF: 状态同步完成，画面恢复预期层级。
@enduml